# 対応方針
# https://github.com/rvl-lab-utoronto/drake-tamp/compare/main...allenapplehead:drake-tamp:main

# Drake をインストールするために Ubuntu 24.04 をベースイメージにする
# https://drake.mit.edu/installation.html#supported-configurations
FROM ubuntu:24.04
# FROM python:3.12-slim-bookworm
# FROM nvidia/cuda:11.1.1-runtime-ubuntu18.04

RUN DEBIAN_FRONTEND=noninteractive
RUN apt-get -y update

RUN apt-get -y install \
    curl \
    wget \
    unzip \
    git cmake vim \
    # Drake の dependencies
    # https://drake.mit.edu/installation.html#supported-configurations
    gcc-13 g++-13 \
    \
    libgl1-mesa-dev libosmesa6-dev patchelf \
    libopenmpi-dev libglew-dev libglfw3 libglfw3-dev

# # for display through vnc
# # ------------------------------------------------------------
# RUN apt-get install -y xfce4 tigervnc-standalone-server

# Install Python 3.12 and drake
# ------------------------------------------------------------
RUN apt-get update && apt-get install -y \
    python3 \
    python3-venv \
    python3-pip

# set python3.12 as default python
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

# ----------------------------------------------------------------------
# Prepare uv
# https://docs.astral.sh/uv/guides/integration/docker/#installing-uv
# ----------------------------------------------------------------------
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# # Prepare packages from pyproject.toml
# COPY environments/experiment/pyproject.toml /${WORKING_DIRECTORY}/pyproject.toml
# https://www.reddit.com/r/learnpython/comments/1hspt62/comment/m5sak3o/?tl=ja
ENV UV_PROJECT_ENVIRONMENT="/usr/local/"
# RUN uv sync



# # # python venv setup with drake
# # RUN mkdir -p /python_venvs/tamp
# # WORKDIR /python_venvs/
# # RUN python3 -m venv tamp --system-site-packages
# # WORKDIR /python_venvs/tamp

# Install ompl for python
RUN wget https://ompl.kavrakilab.org/install-ompl-ubuntu.sh -O /install-ompl-ubuntu.sh \
    && chmod u+x /install-ompl-ubuntu.sh
RUN bash /install-ompl-ubuntu.sh --python

# # # utilities 
# # RUN apt-get -y install firefox
# # RUN apt-get -y install tmux
# # RUN apt-get -y install openssh-server
# # RUN apt-get -y install sudo
# # RUN apt-get -y install xfce4-terminal
# # RUN apt-get -y install gedit
# # RUN apt-get -y install trash-cli
# # RUN apt-get -y install ffmpeg
# # RUN apt-get -y install xdg-utils

# NOTE: They are required to install python-fcl
# # RUN apt-get -y install liboctomap-dev libfcl-dev

# # RUN apt-get -y install apt-transport-https gnupg
# # RUN curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
# # RUN mv bazel.gpg /etc/apt/trusted.gpg.d/ 
# # RUN echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
# # RUN apt update
# # RUN apt-get -y install bazel
# # RUN apt-get -y install jq

# # # pddlstream
# # #RUN git clone --recurse-submodules https://github.com/caelan/pddlstream.git pddlstream
# # #RUN cd pddlstream && ./FastDownward/build.py release64
# # #RUN cd pddlstream/FastDownward/builds && ln -s release64 release32
# # #ENV PYTHONPATH=${PYTHONPATH}:/python_venvs/tamp/pddlstream

# # # update terminal config
# # RUN printf "2\n" | update-alternatives --config x-terminal-emulator

# # # arguments when building image
# # # login password 
# # ARG password 
# # # $UID
# # ARG id
# # # $USER
# # ARG user
# # ENV PASS=$password

# # RUN groupadd -g $id $user
# # RUN useradd -s /bin/bash -u $id -g $id -m $user && echo "$user:$password" | chpasswd && adduser $user sudo
# # RUN chown -R $user /python_venvs
# # ENV PATH="/python_venvs/tamp/bin:$PATH"
# # USER $user

# # WORKDIR /home/$user/
# # # mujoco
# # RUN wget https://www.roboti.us/download/mujoco200_linux.zip -O mujoco.zip
# # RUN unzip mujoco.zip -d .mujoco
# # RUN mv .mujoco/mujoco200_linux .mujoco/mujoco200
# # # add mujoco to LD_LIBRARY_PATH
# # ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/$user/.mujoco/mujoco200/bin

# # WORKDIR /home/$user/
# # # start ikea specific stuff #
# # RUN git clone https://github.com/BenAgro314/furniture.git
# # WORKDIR /home/$user/furniture
# # RUN git fetch origin aug2020_fixes:aug2020_fixes
# # RUN git checkout aug2020_fixes
# # RUN ln -s /home/$user/.mujoco/mujoco200 /home/$user/.mujoco/mujoco200_linux
# # #RUN pip install --upgrade pip
# # RUN pip3 install scikit-build
# # RUN pip3 install glfw>=1.4.0 numpy>=1.19.5 Cython>=0.27.2 imageio>=2.1.2 cffi>=1.10 fasteners~=0.15 lockfile

# # RUN pip3 install -r requirements.txt

# # WORKDIR /home/$user/
# # # other requirements
# # COPY requirements.txt requirements.txt
# # RUN pip3 install -r requirements.txt
# # RUN pip3 install torch==1.9.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
# # RUN pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html
# # ENV PYTHONPATH=${PYTHONPATH}:/home/$user/drake-tamp/:/home/$user/drake-tamp/pddlstream/:/home/$user/furniture/:/home/$user/drake-tamp/experiments/ikea_induction/

# # RUN echo "source /python_venvs/tamp/bin/activate" >> ~/.bashrc
# # RUN echo "export  USER=$user" >> ~/.bashrc
# # RUN echo "export  PYTHONPATH=${PYTHONPATH}:/home/$user/drake-tamp/:/home/$user/drake-tamp/pddlstream/:/home/$user/experiments/ikea_induction/:/home/$user/drake-tamp/pddlstream/examples/pybullet/utils/" >> ~/.bashrc
# # RUN echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/$user/.mujoco/mujoco200/bin" >> ~/.bashrc

# ARG gitname 
# ARG gitemail 

# RUN git config --global user.name $gitname
# RUN git config --global user.email $gitemail

# WORKDIR /home/$user/drake-tamp
# COPY .tmux.conf /home/$user/.tmux.conf
# COPY .vimrc /home/$user/.vimrc

# COPY entrypoint.sh /entrypoint.sh
# ENTRYPOINT ["bash","/entrypoint.sh"]

# CMD ["bash"]
