# This should be used only once because it takes a long time to build the image.
# After building this image, you can use it as a base image for other images.
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN rm -rf /var/lib/apt/lists/* \
    && apt -y update && apt -y install --no-install-recommends \
    wget \
    \
    # * gcc and g++ are required for installing ompl and it has to be version 11.
    # Drake also requires them and the latest one requires version 13 for installing drake 1.51.0.
    # * As there is the conflict between ompl and drake, we will install gcc-11 and g++-11
    # and we decided to use drake==1.48.0 which is the latest version that supports gcc-11.
    # [Reference]
    # https://drake.mit.edu/installation.html#supported-configurations
    # Starting with the drake 1.49.0, support for gcc-13 is required.
    # https://drake.mit.edu/release_notes/v1.49.0.html
    gcc-11 g++-11 \
    \
    python3 \
    python3-dev \
    python3-setuptools \
    \
    # Required for building ompl.
    libassimp-dev \
    libccd-dev \
    libgl-dev \
    libglx-dev \
    libfcl-dev \
    \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100 \
    && update-alternatives --install /usr/bin/cc  cc  /usr/bin/gcc-11 100 \
    && update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-11 100 \
    && rm -rf /var/lib/apt/lists/* \
    && apt -y autoremove


# HACK: Packages installed in install-ompl-ubuntu.sh
RUN apt -y update && apt -y install --no-install-recommends \
    # install_common_dependencies
    cmake \
    libboost-filesystem-dev \
    libboost-program-options-dev \
    libboost-serialization-dev \
    libboost-system-dev \
    libboost-test-dev \
    libeigen3-dev \
    libexpat1 \
    libtriangle-dev \
    ninja-build \
    pkg-config \
    # install_python_binding_dependencies
    # castxml is used in installation of ompl.
    castxml \
    # # clang is required by castxml to parse C++ headers for binding generation.
    # clang \
    libboost-numpy-dev \
    libboost-python-dev \
    python3-pip \
    # python3-celery \
    # python3-flask \
    # python3-numpy \
    python3-opengl \
    python3-pyqt5.qtopengl \
    # pypy3 \
    && rm -rf /var/lib/apt/lists/* \
    && apt -y autoremove
    # && export CXX=clang++


# RUN && ${SUDO} pip3 install ${PIP_ARGS} -vU https://github.com/CastXML/pygccxml/archive/develop.zip pyplusplus
RUN pip install --break-system-packages \
    Babel==2.10.3 pyplusplus==1.8.7 pygccxml==3.0.2 celery==5.3.6 \
    PyOpenGL==3.1.7 Flask==3.0.2 PyQt5==5.15.10 PyQt5-sip==12.13.0 \
    setuptools==68.1.2 numpy==1.26.4


# Install ompl for python
# RUN wget https://ompl.kavrakilab.org/install-ompl-ubuntu.sh -O /install-ompl-ubuntu.sh \
#     && chmod u+x /install-ompl-ubuntu.sh
# RUN /install-ompl-ubuntu.sh --python \
#     && rm /install-ompl-ubuntu.sh
RUN wget -O - https://github.com/ompl/ompl/archive/1.7.0.tar.gz | tar zxf - \
    && cd ompl-1.7.0 \
    && cmake \
        -G Ninja \
        -B build \
        -DPYTHON_EXEC=/usr/bin/python3 \
        -DOMPL_REGISTRATION=OFF \
        # spot（時相論理ライブラリ: libspot）が Ubuntu 24.04 の標準リポジトリにない為無効化
        -DOMPLAPP_WITH_SPOT=OFF \
        -DCMAKE_INSTALL_PREFIX=/usr && \
    cmake --build build -t update_bindings || echo "Warning: Binding generation failed, but continuing..." && \
    cmake --build build && \
    cmake --install build
